//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : Sm.sm
//

#ifndef SM_SM_H
#define SM_SM_H


#define SMC_USES_IOSTREAMS

#include <statemap.h>

// Forward declarations.
class Map1;
class Map1_Start;
class Map1_charI;
class Map1_charIn;
class Map1_charInt;
class Map1_charS;
class Map1_charSh;
class Map1_charSho;
class Map1_charShor;
class Map1_charShort;
class Map1_charL;
class Map1_charLo;
class Map1_charLon;
class Map1_charLong;
class Map1_NameFirst;
class Map1_NameRest;
class Map1_CountFirst;
class Map1_CountRest;
class Map1_ExpectEqual;
class Map1_ExpectLBrace;
class Map1_LitStart;
class Map1_LitAfterMinus;
class Map1_LitDigits;
class Map1_final;
class Map1_Suc;
class Map1_Error;
class Map1_Default;
class AppClassState;
class SmContext;
class AppClass;

class AppClassState :
    public statemap::State
{
public:

    AppClassState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(SmContext&) {};
    virtual void Exit(SmContext&) {};

    virtual void EOS(SmContext& context);
    virtual void symbol(SmContext& context, char c);

protected:

    virtual void Default(SmContext& context);
};

class Map1
{
public:

    static Map1_Start Start;
    static Map1_charI charI;
    static Map1_charIn charIn;
    static Map1_charInt charInt;
    static Map1_charS charS;
    static Map1_charSh charSh;
    static Map1_charSho charSho;
    static Map1_charShor charShor;
    static Map1_charShort charShort;
    static Map1_charL charL;
    static Map1_charLo charLo;
    static Map1_charLon charLon;
    static Map1_charLong charLong;
    static Map1_NameFirst NameFirst;
    static Map1_NameRest NameRest;
    static Map1_CountFirst CountFirst;
    static Map1_CountRest CountRest;
    static Map1_ExpectEqual ExpectEqual;
    static Map1_ExpectLBrace ExpectLBrace;
    static Map1_LitStart LitStart;
    static Map1_LitAfterMinus LitAfterMinus;
    static Map1_LitDigits LitDigits;
    static Map1_final final;
    static Map1_Suc Suc;
    static Map1_Error Error;
};

class Map1_Default :
    public AppClassState
{
public:

    Map1_Default(const char * const name, const int stateId)
    : AppClassState(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
    virtual void EOS(SmContext& context);
};

class Map1_Start :
    public Map1_Default
{
public:
    Map1_Start(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_charI :
    public Map1_Default
{
public:
    Map1_charI(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_charIn :
    public Map1_Default
{
public:
    Map1_charIn(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_charInt :
    public Map1_Default
{
public:
    Map1_charInt(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_charS :
    public Map1_Default
{
public:
    Map1_charS(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_charSh :
    public Map1_Default
{
public:
    Map1_charSh(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_charSho :
    public Map1_Default
{
public:
    Map1_charSho(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_charShor :
    public Map1_Default
{
public:
    Map1_charShor(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_charShort :
    public Map1_Default
{
public:
    Map1_charShort(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_charL :
    public Map1_Default
{
public:
    Map1_charL(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_charLo :
    public Map1_Default
{
public:
    Map1_charLo(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_charLon :
    public Map1_Default
{
public:
    Map1_charLon(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_charLong :
    public Map1_Default
{
public:
    Map1_charLong(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_NameFirst :
    public Map1_Default
{
public:
    Map1_NameFirst(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_NameRest :
    public Map1_Default
{
public:
    Map1_NameRest(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_CountFirst :
    public Map1_Default
{
public:
    Map1_CountFirst(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_CountRest :
    public Map1_Default
{
public:
    Map1_CountRest(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_ExpectEqual :
    public Map1_Default
{
public:
    Map1_ExpectEqual(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_ExpectLBrace :
    public Map1_Default
{
public:
    Map1_ExpectLBrace(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_LitStart :
    public Map1_Default
{
public:
    Map1_LitStart(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_LitAfterMinus :
    public Map1_Default
{
public:
    Map1_LitAfterMinus(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_LitDigits :
    public Map1_Default
{
public:
    Map1_LitDigits(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void symbol(SmContext& context, char c);
};

class Map1_final :
    public Map1_Default
{
public:
    Map1_final(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

    virtual void EOS(SmContext& context);
};

class Map1_Suc :
    public Map1_Default
{
public:
    Map1_Suc(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

};

class Map1_Error :
    public Map1_Default
{
public:
    Map1_Error(const char * const name, const int stateId)
    : Map1_Default(name, stateId)
    {};

};

class SmContext :
    public statemap::FSMContext
{
public:

    explicit SmContext(AppClass& owner)
    : FSMContext(Map1::Start),
      _owner(owner)
    {};

    SmContext(AppClass& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline AppClass& getOwner()
    {
        return (_owner);
    };

    inline AppClassState& getState()
    {
        if (_state == NULL)
        {
            throw statemap::StateUndefinedException();
        }

        return dynamic_cast<AppClassState&>(*_state);
    };

    inline void EOS()
    {
        getState().EOS(*this);
    };

    inline void symbol(char c)
    {
        getState().symbol(*this, c);
    };

private:
    AppClass& _owner;
};


#endif // SM_SM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
