//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : Sm.sm
//

#include "AppClass.h"
#include "Sm_sm.h"

using namespace statemap;

// Static class declarations.
Map1_Start Map1::Start("Map1::Start", 0);
Map1_charI Map1::charI("Map1::charI", 1);
Map1_charIn Map1::charIn("Map1::charIn", 2);
Map1_charInt Map1::charInt("Map1::charInt", 3);
Map1_charS Map1::charS("Map1::charS", 4);
Map1_charSh Map1::charSh("Map1::charSh", 5);
Map1_charSho Map1::charSho("Map1::charSho", 6);
Map1_charShor Map1::charShor("Map1::charShor", 7);
Map1_charShort Map1::charShort("Map1::charShort", 8);
Map1_charL Map1::charL("Map1::charL", 9);
Map1_charLo Map1::charLo("Map1::charLo", 10);
Map1_charLon Map1::charLon("Map1::charLon", 11);
Map1_charLong Map1::charLong("Map1::charLong", 12);
Map1_NameFirst Map1::NameFirst("Map1::NameFirst", 13);
Map1_NameRest Map1::NameRest("Map1::NameRest", 14);
Map1_CountFirst Map1::CountFirst("Map1::CountFirst", 15);
Map1_CountRest Map1::CountRest("Map1::CountRest", 16);
Map1_ExpectEqual Map1::ExpectEqual("Map1::ExpectEqual", 17);
Map1_ExpectLBrace Map1::ExpectLBrace("Map1::ExpectLBrace", 18);
Map1_LitStart Map1::LitStart("Map1::LitStart", 19);
Map1_LitAfterMinus Map1::LitAfterMinus("Map1::LitAfterMinus", 20);
Map1_LitDigits Map1::LitDigits("Map1::LitDigits", 21);
Map1_final Map1::final("Map1::final", 22);
Map1_Suc Map1::Suc("Map1::Suc", 23);
Map1_Error Map1::Error("Map1::Error", 24);

void AppClassState::EOS(SmContext& context)
{
    Default(context);
}

void AppClassState::symbol(SmContext& context, char c)
{
    Default(context);
}

void AppClassState::Default(SmContext& context)
{
    throw (
        TransitionUndefinedException(
            (context.getState()).getName(),
            context.getTransition()));

}

void Map1_Default::symbol(SmContext& context, char c)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.error();
        context.setState(Map1::Error);
    }
    catch (...)
    {
        context.setState(Map1::Error);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Default::EOS(SmContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.error();
        context.setState(Map1::Error);
    }
    catch (...)
    {
        context.setState(Map1::Error);
        throw;
    }
    context.getState().Entry(context);


}

void Map1_Start::symbol(SmContext& context, char c)
{

    if (c == 'i')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::charI);
        context.getState().Entry(context);
    }
    else if (c == 's')

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::charS);
        context.getState().Entry(context);
    }
    else if (c == 'l')

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::charL);
        context.getState().Entry(context);
    }    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_charI::symbol(SmContext& context, char c)
{

    if (c == 'n')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::charIn);
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_charIn::symbol(SmContext& context, char c)
{

    if (c == 't')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::charInt);
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_charInt::symbol(SmContext& context, char c)
{
    AppClass& ctxt = context.getOwner();

    if (c == ' ')
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.setTypeInt();
            context.setState(Map1::NameFirst);
        }
        catch (...)
        {
            context.setState(Map1::NameFirst);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_charS::symbol(SmContext& context, char c)
{

    if (c == 'h')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::charSh);
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_charSh::symbol(SmContext& context, char c)
{

    if (c == 'o')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::charSho);
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_charSho::symbol(SmContext& context, char c)
{

    if (c == 'r')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::charShor);
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_charShor::symbol(SmContext& context, char c)
{

    if (c == 't')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::charShort);
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_charShort::symbol(SmContext& context, char c)
{
    AppClass& ctxt = context.getOwner();

    if (c == ' ')
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.setTypeShort();
            context.setState(Map1::NameFirst);
        }
        catch (...)
        {
            context.setState(Map1::NameFirst);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_charL::symbol(SmContext& context, char c)
{

    if (c == 'o')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::charLo);
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_charLo::symbol(SmContext& context, char c)
{

    if (c == 'n')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::charLon);
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_charLon::symbol(SmContext& context, char c)
{

    if (c == 'g')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::charLong);
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_charLong::symbol(SmContext& context, char c)
{
    AppClass& ctxt = context.getOwner();

    if (c == ' ')
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.setTypeLong();
            context.setState(Map1::NameFirst);
        }
        catch (...)
        {
            context.setState(Map1::NameFirst);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_NameFirst::symbol(SmContext& context, char c)
{
    AppClass& ctxt = context.getOwner();

    if (ctxt.isLetter(c))
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.addNameChar(c);
            context.setState(Map1::NameRest);
        }
        catch (...)
        {
            context.setState(Map1::NameRest);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_NameRest::symbol(SmContext& context, char c)
{
    AppClass& ctxt = context.getOwner();

    if (ctxt.isAlnum(c) && ctxt.nameLen() < 16)
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.addNameChar(c);
            context.setState(Map1::NameRest);
        }
        catch (...)
        {
            context.setState(Map1::NameRest);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (c == 91)

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::CountFirst);
        context.getState().Entry(context);
    }    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_CountFirst::symbol(SmContext& context, char c)
{
    AppClass& ctxt = context.getOwner();

    if (ctxt.isNonZero(c))
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.addCountChar(c);
            context.setState(Map1::CountRest);
        }
        catch (...)
        {
            context.setState(Map1::CountRest);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_CountRest::symbol(SmContext& context, char c)
{
    AppClass& ctxt = context.getOwner();

    if (ctxt.isDigit(c) && ctxt.countLen() < 9)
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.addCountChar(c);
            context.setState(Map1::CountRest);
        }
        catch (...)
        {
            context.setState(Map1::CountRest);
            throw;
        }
        context.getState().Entry(context);
    }
    else if (c == 93)

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::ExpectEqual);
        context.getState().Entry(context);
    }    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_ExpectEqual::symbol(SmContext& context, char c)
{

    if (c == '=')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::ExpectLBrace);
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_ExpectLBrace::symbol(SmContext& context, char c)
{

    if (c == '{')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::LitStart);
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_LitStart::symbol(SmContext& context, char c)
{
    AppClass& ctxt = context.getOwner();

    if (c == '-')
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::LitAfterMinus);
        context.getState().Entry(context);
    }
    else if (ctxt.isDigit(c))

    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.incLit();
            context.setState(Map1::LitDigits);
        }
        catch (...)
        {
            context.setState(Map1::LitDigits);
            throw;
        }
        context.getState().Entry(context);
    }    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_LitAfterMinus::symbol(SmContext& context, char c)
{
    AppClass& ctxt = context.getOwner();

    if (ctxt.isDigit(c))
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.incLit();
            context.setState(Map1::LitDigits);
        }
        catch (...)
        {
            context.setState(Map1::LitDigits);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_LitDigits::symbol(SmContext& context, char c)
{
    AppClass& ctxt = context.getOwner();

    if (ctxt.isDigit(c))
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::LitDigits);
        context.getState().Entry(context);
    }
    else if (c == ',')

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::LitStart);
        context.getState().Entry(context);
    }
    else if (c == '}')

    {
        context.getState().Exit(context);
        // No actions.
        context.setState(Map1::final);
        context.getState().Entry(context);
    }    else
    {
         Map1_Default::symbol(context, c);
    }


}

void Map1_final::EOS(SmContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.Suc();
        context.setState(Map1::Suc);
    }
    catch (...)
    {
        context.setState(Map1::Suc);
        throw;
    }
    context.getState().Entry(context);


}

//
// Local variables:
//  buffer-read-only: t
// End:
//
